-- pembilang------------------------
INSERT INTO DataDasar(nama) VALUES('Test');
INSERT INTO DataDasar(nama) VALUES('Jumlah prodi terakreditasi internasional');
INSERT INTO DataDasar(nama) VALUES('-');
INSERT INTO DataDasar(nama) VALUES('Jumlah Penelitian dengan Mitra dari PT Luar Negeri');
INSERT INTO DataDasar(nama) VALUES('Jumlah Dosen');
INSERT INTO DataDasar(nama) VALUES('Jumlah Penelitian Kerjasama Internasional');
INSERT INTO DataDasar(nama) VALUES('Jumlah Program Studi Terakreditasi A');
INSERT INTO DataDasar(nama) VALUES('Jumlah Program Studi');
INSERT INTO DataDasar(nama) VALUES('Jumlah Publikasi di Jurnal Internasional Terindeks Scopus atau minimum setara');
INSERT INTO DataDasar(nama) VALUES('Jumlah Publikasi di Jurnal Internasional Terindeks Scopus atau minimum setara sebagai penulis pertama atau corresponding author');
INSERT INTO DataDasar(nama) VALUES('Jumlah Publikasi Internasional Terindeks Scopus atau minimum setara');
INSERT INTO DataDasar(nama) VALUES('Jumlah Publikasi Internasional Terindeks Scopus kumulatif');
INSERT INTO DataDasar(nama) VALUES('Jumlah Sitasi dari Publikasi Internasional Terindeks Scopus kumulatif');
INSERT INTO DataDasar(nama) VALUES('Total Nilai H-index Scopus Dosen');
INSERT INTO DataDasar(nama) VALUES('Jumlah kejuaraan ranking 1 di lomba tingkat nasional yang diraih Mahasiswa atau Tim Mahasiswa');
INSERT INTO DataDasar(nama) VALUES('Jumlah Penghargaan diterima Dosen di kegiatan Berskala Nasional');
INSERT INTO DataDasar(nama) VALUES('Jumlah tim ilmiah kemahasiswaan yang didanai dalam rangka PIMNAS');
INSERT INTO DataDasar(nama) VALUES('');
INSERT INTO DataDasar(nama) VALUES('Jumlah Judul Penelitian');
INSERT INTO DataDasar(nama) VALUES('Jumlah judul penelitian yang Diketuai oleh Dosen');
INSERT INTO DataDasar(nama) VALUES('jumlah lulusan Program S3 tepat waktu');
INSERT INTO DataDasar(nama) VALUES('Jumlah lulusan Program S3');
INSERT INTO DataDasar(nama) VALUES('Jumlah mahasiswa yang mendapatkan sertifikasi kompetensi');
INSERT INTO DataDasar(nama) VALUES('Jumlah Mahasiswa');
INSERT INTO DataDasar(nama) VALUES('Jumlah Publikasi Bersama (Co-Authorship) Internasional kumulatif');
INSERT INTO DataDasar(nama) VALUES('mata kuliah daring synchronous (blended learning)');
INSERT INTO DataDasar(nama) VALUES('jumlah lulusan Program S2 tepat waktu');
INSERT INTO DataDasar(nama) VALUES('Jumlah lulusan Program S2');
INSERT INTO DataDasar(nama) VALUES('Jumlah mahasiswa berwirausaha');
INSERT INTO DataDasar(nama) VALUES('Jumlah Mahasiswa S1 atau D4');
INSERT INTO DataDasar(nama) VALUES('jumlah lulusan Program S1 atau D4 tepat waktu');
INSERT INTO DataDasar(nama) VALUES('Jumlah lulusan Program S1 atau D4');
INSERT INTO DataDasar(nama) VALUES('Jumlah Paper di Jurnal Nasional Terakreditasi');
INSERT INTO DataDasar(nama) VALUES('Jumlah Publikasi di Seminar Internasional Terindeks Scopus');
INSERT INTO DataDasar(nama) VALUES('Jumlah lulusan yang langsung bekerja dalam jangka waktu 1 tahun setelah kelulusan');
INSERT INTO DataDasar(nama) VALUES('Jumlah lulusan');
INSERT INTO DataDasar(nama) VALUES('mata kuliah daring asynchronous (MOOC)');
INSERT INTO DataDasar(nama) VALUES('Jumlah mahasiswa yang berprestasi (Juara 1, 2, dan 3 ) ditingkat Nasional (lomba kelompok)');
INSERT INTO DataDasar(nama) VALUES('Jumlah mahasiswa yang berprestasi (Juara 1, 2, dan 3 ) ditingkat Nasional (lomba perseorangan)');
INSERT INTO DataDasar(nama) VALUES('Jumlah kejuaraan di lomba tingkat internasional yang dijuarai Mahasiswa ITS');
INSERT INTO DataDasar(nama) VALUES('Jumlah Dosen yang Diundang sebagai Invited atau Keynote Speaker di Seminar Internasional atau Narasumber');
INSERT INTO DataDasar(nama) VALUES('Jumlah Dosen yang menjadi Editor publikasi Internasional terindeks global');
INSERT INTO DataDasar(nama) VALUES('Jumlah Penghargaan diterima Dosen di kegiatan Berskala Internasional');
INSERT INTO DataDasar(nama) VALUES('Jumlah mahasiswa inbound');
INSERT INTO DataDasar(nama) VALUES('Jumlah Kegiatan Internasional yang Diselenggarakan (kuliah tamu, workshop dan seminar internasional)');
INSERT INTO DataDasar(nama) VALUES('Jumlah mahasiswa yang berprestasi (Juara 1, 2, dan 3 ) ditingkat Internasional (lomba kelompok)');
INSERT INTO DataDasar(nama) VALUES('Jumlah mahasiswa yang berprestasi (Juara 1, 2, dan 3 ) ditingkat Internasional (lomba perseorangan)');
INSERT INTO DataDasar(nama) VALUES('Jumlah Dosen yang menjadi Reviewer publikasi Internasional terindeks global');
INSERT INTO DataDasar(nama) VALUES('Jumlah mahasiswa outbound');
INSERT INTO DataDasar(nama) VALUES('Jumlah Dosen yang menjadi Anggota Asosiasi Profesi Internasional');
INSERT INTO DataDasar(nama) VALUES('Jumlah prodi yang menyelenggarakan Kelas Internasional');
INSERT INTO DataDasar(nama) VALUES('Jumlah Temuan Irjen/BPK/KAI');
INSERT INTO DataDasar(nama) VALUES('Jumlah Mahasiswa Pascasarjana');
INSERT INTO DataDasar(nama) VALUES('Jumlah Visiting Professor,Lecturer,Researcher ke PTLN mitra');
INSERT INTO DataDasar(nama) VALUES('Jumlah dosen memperoleh sertifikasi kompetensi/profesional nasional atau internasional');
INSERT INTO DataDasar(nama) VALUES('Jumlah mahasiswa yang mengikuti kegiatan merdeka belajar');
INSERT INTO DataDasar(nama) VALUES('Jumlah nama PTLN mitra yang mengisi kuesioner QS');
INSERT INTO DataDasar(nama) VALUES('Jumlah Pendaftaran HKI atau Paten (nominal)');
INSERT INTO DataDasar(nama) VALUES('Jumlah prodi yang menerapkan pembelajaran Kampus Merdeka');
INSERT INTO DataDasar(nama) VALUES('Jumlah sertifikasi LBE (lab based education)');
INSERT INTO DataDasar(nama) VALUES('Jumlah Mahasiswa S1 Baru Berbeasiswa Afirmasi (termasuk program bidik misi atau kartu indonesia pintar)');
INSERT INTO DataDasar(nama) VALUES('Jumlah Mahasiswa Baru S1');
INSERT INTO DataDasar(nama) VALUES('Jumlah Mahasiswa S3 yang teregistrasi');
INSERT INTO DataDasar(nama) VALUES('Jumlah Revenue dari Mahasiswa (SPP)');
INSERT INTO DataDasar(nama) VALUES('Jumlah Mahasiswa (Program Pasca Sarjana)');
INSERT INTO DataDasar(nama) VALUES('Jumlah mahasiswa yang mengikuti program magang industri');
INSERT INTO DataDasar(nama) VALUES('Jumlah layanan yang telah diintegrasikan dengan layanan ULT (Unit Layanan Terpadu)');
INSERT INTO DataDasar(nama) VALUES('Jumlah Mahasiswa S2 yang teregistrasi');
INSERT INTO DataDasar(nama) VALUES('Jumlah Visiting Professor/Lecturer/Researcher dari PTLN mitra');
INSERT INTO DataDasar(nama) VALUES('Ketersediaan profil unit berupa PPT dan video (dalam bahasa Indonesia dan English)');
INSERT INTO DataDasar(nama) VALUES('jumlah buku ber-ISBN dan dipasarkan kumulatif 3 tahun terakhir)');
INSERT INTO DataDasar(nama) VALUES('Jumlah Revenue dari Mahasiswa (UKT, SPI, SPP)');
INSERT INTO DataDasar(nama) VALUES('Tingkat Maturitas Penyelenggaraan Sistem Pengendalian Intern Pemerintah (SPIP)');
INSERT INTO DataDasar(nama) VALUES('Jumlah kelas mata kuliah/praktikum yang dikelola atau dilayani oleh Laboratorium');
INSERT INTO DataDasar(nama) VALUES('Jumlah Mahasiswa yang terlibat dalam penelitian Dosen');
INSERT INTO DataDasar(nama) VALUES('Jumlah Prodi Baru');
INSERT INTO DataDasar(nama) VALUES('Jumlah Departemen');
INSERT INTO DataDasar(nama) VALUES('jumlah dosen yang mengalami kenaikan jabatan fungsional');
INSERT INTO DataDasar(nama) VALUES('jumlah dosen (diluar gol IV-E)');
INSERT INTO DataDasar(nama) VALUES('Jumlah Dosen yang Mulai Mengikuti Pendidikan S3 Pada Tahun Berjalan');
INSERT INTO DataDasar(nama) VALUES('Jumlah Dosen Bergelar S2 non TB+IB');
INSERT INTO DataDasar(nama) VALUES('Jumlah Dosen dalam Jabatan Lektor Kepala');
INSERT INTO DataDasar(nama) VALUES('Jumlah Dosen dalam Jabatan Profesor');
INSERT INTO DataDasar(nama) VALUES('Jumlah dosen yang memiliki pengalaman bekerja di industri atau lembaga profesi minimal 1 tahun dan/atau bekerja di luar negeri minimal 1 tahun');
INSERT INTO DataDasar(nama) VALUES('Jumlah Dosen bergelar S3');
INSERT INTO DataDasar(nama) VALUES('jumlah dosen PNS dan NON-PNS yang mendapatkan jabatan fungsional pertama');
INSERT INTO DataDasar(nama) VALUES('jumlah dosen PNS dan NON-PNS yang belum punya jabatan fungsional');
INSERT INTO DataDasar(nama) VALUES('Jumlah Dosen yang Mengikuti Pelatihan atau Workshop');
INSERT INTO DataDasar(nama) VALUES('Jumlah Tenaga Kependidikan yang Mengikuti Pelatihan atau Workshop');
INSERT INTO DataDasar(nama) VALUES('Jumlah Tenaga Kependidikan');
INSERT INTO DataDasar(nama) VALUES('Rata-rata waktu dosen mendapatkan jabatan fungsional pertama');
INSERT INTO DataDasar(nama) VALUES('Terlaksananya Indeks Kualitas Lingkungan dan K3L lebih dari 2');
INSERT INTO DataDasar(nama) VALUES('Terlaksananya toilet bersih lebih dari 80% ');
INSERT INTO DataDasar(nama) VALUES('Terlaksananya program 3 R Sampah (Reduce, Reuse, Recycle)');
INSERT INTO DataDasar(nama) VALUES('Jumlah kegiatan pengabdian kepada masyarakat yang Diketuai Dosen Lab terkait');
INSERT INTO DataDasar(nama) VALUES('Jumlah Kerjasama dengan Industri yang diketuai Dosen dari Lab terkait');
INSERT INTO DataDasar(nama) VALUES('Nilai Kerjasama dengan Industri dengan kontrak atas nama ITS  (Rp juta)');
INSERT INTO DataDasar(nama) VALUES('Jumlah mahasiswa yang terlibat dalam pengabdian Dosen');