-- pembilang------------------------
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Test',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah prodi terakreditasi internasional',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('-',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Penelitian dengan Mitra dari PT Luar Negeri',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Dosen',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Penelitian Kerjasama Internasional',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Program Studi Terakreditasi A',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Program Studi',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Publikasi di Jurnal Internasional Terindeks Scopus atau minimum setara',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Publikasi di Jurnal Internasional Terindeks Scopus atau minimum setara sebagai penulis pertama atau corresponding author',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Publikasi Internasional Terindeks Scopus atau minimum setara',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Publikasi Internasional Terindeks Scopus kumulatif',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Sitasi dari Publikasi Internasional Terindeks Scopus kumulatif',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Total Nilai H-index Scopus Dosen',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah kejuaraan ranking 1 di lomba tingkat nasional yang diraih Mahasiswa atau Tim Mahasiswa',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Penghargaan diterima Dosen di kegiatan Berskala Nasional',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah tim ilmiah kemahasiswaan yang didanai dalam rangka PIMNAS',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Judul Penelitian',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah judul penelitian yang Diketuai oleh Dosen',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('jumlah lulusan Program S3 tepat waktu',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah lulusan Program S3',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah mahasiswa yang mendapatkan sertifikasi kompetensi',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Mahasiswa',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Publikasi Bersama (Co-Authorship) Internasional kumulatif',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('mata kuliah daring synchronous (blended learning)',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('jumlah lulusan Program S2 tepat waktu',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah lulusan Program S2',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah mahasiswa berwirausaha',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Mahasiswa S1 atau D4',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('jumlah lulusan Program S1 atau D4 tepat waktu',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah lulusan Program S1 atau D4',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Paper di Jurnal Nasional Terakreditasi',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Publikasi di Seminar Internasional Terindeks Scopus',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah lulusan yang langsung bekerja dalam jangka waktu 1 tahun setelah kelulusan',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah lulusan',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('mata kuliah daring asynchronous (MOOC)',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah mahasiswa yang berprestasi (Juara 1, 2, dan 3 ) ditingkat Nasional (lomba kelompok)',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah mahasiswa yang berprestasi (Juara 1, 2, dan 3 ) ditingkat Nasional (lomba perseorangan)',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah kejuaraan di lomba tingkat internasional yang dijuarai Mahasiswa ITS',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Dosen yang Diundang sebagai Invited atau Keynote Speaker di Seminar Internasional atau Narasumber',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Dosen yang menjadi Editor publikasi Internasional terindeks global',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Penghargaan diterima Dosen di kegiatan Berskala Internasional',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah mahasiswa inbound',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Kegiatan Internasional yang Diselenggarakan (kuliah tamu, workshop dan seminar internasional)',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah mahasiswa yang berprestasi (Juara 1, 2, dan 3 ) ditingkat Internasional (lomba kelompok)',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah mahasiswa yang berprestasi (Juara 1, 2, dan 3 ) ditingkat Internasional (lomba perseorangan)',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Dosen yang menjadi Reviewer publikasi Internasional terindeks global',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah mahasiswa outbound',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Dosen yang menjadi Anggota Asosiasi Profesi Internasional',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah prodi yang menyelenggarakan Kelas Internasional',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Temuan Irjen/BPK/KAI',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Mahasiswa Pascasarjana',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Visiting Professor,Lecturer,Researcher ke PTLN mitra',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah dosen memperoleh sertifikasi kompetensi/profesional nasional atau internasional',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah mahasiswa yang mengikuti kegiatan merdeka belajar',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah nama PTLN mitra yang mengisi kuesioner QS',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Pendaftaran HKI atau Paten (nominal)',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah prodi yang menerapkan pembelajaran Kampus Merdeka',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah sertifikasi LBE (lab based education)',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Mahasiswa S1 Baru Berbeasiswa Afirmasi (termasuk program bidik misi atau kartu indonesia pintar)',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Mahasiswa Baru S1',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Mahasiswa S3 yang teregistrasi',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Revenue dari Mahasiswa (SPP)',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Mahasiswa (Program Pasca Sarjana)',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah mahasiswa yang mengikuti program magang industri',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah layanan yang telah diintegrasikan dengan layanan ULT (Unit Layanan Terpadu)',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Mahasiswa S2 yang teregistrasi',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Visiting Professor/Lecturer/Researcher dari PTLN mitra',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Ketersediaan profil unit berupa PPT dan video (dalam bahasa Indonesia dan English)',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('jumlah buku ber-ISBN dan dipasarkan kumulatif 3 tahun terakhir)',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Revenue dari Mahasiswa (UKT, SPI, SPP)',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Tingkat Maturitas Penyelenggaraan Sistem Pengendalian Intern Pemerintah (SPIP)',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah kelas mata kuliah/praktikum yang dikelola atau dilayani oleh Laboratorium',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Mahasiswa yang terlibat dalam penelitian Dosen',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Prodi Baru',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Departemen',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('jumlah dosen yang mengalami kenaikan jabatan fungsional',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('jumlah dosen (diluar gol IV-E)',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Dosen yang Mulai Mengikuti Pendidikan S3 Pada Tahun Berjalan',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Dosen Bergelar S2 non TB+IB',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Dosen dalam Jabatan Lektor Kepala',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Dosen dalam Jabatan Profesor',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah dosen yang memiliki pengalaman bekerja di industri atau lembaga profesi minimal 1 tahun dan/atau bekerja di luar negeri minimal 1 tahun',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Dosen bergelar S3',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('jumlah dosen PNS dan NON-PNS yang mendapatkan jabatan fungsional pertama',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('jumlah dosen PNS dan NON-PNS yang belum punya jabatan fungsional',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Dosen yang Mengikuti Pelatihan atau Workshop',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Tenaga Kependidikan yang Mengikuti Pelatihan atau Workshop',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Tenaga Kependidikan',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Rata-rata waktu dosen mendapatkan jabatan fungsional pertama',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Terlaksananya Indeks Kualitas Lingkungan dan K3L lebih dari 2',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Terlaksananya toilet bersih lebih dari 80% ',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Terlaksananya program 3 R Sampah (Reduce, Reuse, Recycle)',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah kegiatan pengabdian kepada masyarakat yang Diketuai Dosen Lab terkait',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah Kerjasama dengan Industri yang diketuai Dosen dari Lab terkait',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Nilai Kerjasama dengan Industri dengan kontrak atas nama ITS  (Rp juta)',Getdate(),Getdate());
INSERT INTO DataDasar(nama,create_date,last_update) VALUES('Jumlah mahasiswa yang terlibat dalam pengabdian Dosen',Getdate(),Getdate());