insert into JenisSatker(nama,create_date,last_update)values('Rektor',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Majelis Wali Amanat',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Senat Akademik',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Wakil Rektor',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Sekretaris Institut',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Fakultas',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Sekolah',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Direktorat',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Biro',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Lembaga',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Kantor',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Badan',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Departemen',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Program Studi',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Laboratorium',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Studio',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Bengkel',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Unit Pelaksana Teknis',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Perpustakaan',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Pusat Studi',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Pusat Lain-lain',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Subdirektorat',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Seksi',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Bagian',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Subbagian',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Unit',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Subunit',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Komite',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Unit Usaha Komersial',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Unit Usaha Penunjang',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Pembantu Rektor',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Dewan',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Pusat Penelitian',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Pusat Unggulan IPTEK',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Pusat Kajian',Getdate(),Getdate())
insert into JenisSatker(nama,create_date,last_update)values('Institut',Getdate(),Getdate())